# GitHub CI for the python project, including building, linting and docker image creation
name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

  docker_build:
    name: docker build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check secrets
        env:
          DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        run: echo $DOCKER_HUB
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker build -t ${{ secrets.DOCKER_HUB }}/${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::7} .
      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker push ${{ secrets.DOCKER_HUB }}/${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::7}

  docker_push:
    name: docker push
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          docker push ${{ secrets.DOCKER_HUB }}/${{ secrets.IMAGE_NAME }}:${GITHUB_REF/refs\/tags\//}

