# GitHub CI for the python project, including building, linting and docker image creation
name: CI
on
  push
    branches
      - master
  pull_request
    branches
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

  docker_build:
    name: docker build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker build -t ${{ secrets.DOCKER_HUB }}/${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::7} .

  docker_push:
    name: docker push
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          docker push ${{ secrets.DOCKER_HUB }}/${{ secrets.IMAGE_NAME }}:${GITHUB_REF/refs\/tags\//}

