name: GHCR working flow
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

  docker_build:
    name: docker build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker build -t ghcr.io/aisuko/${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::7} .
      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker push ghcr.io/aisuko/${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::7}
